include theme.conf
include kitty.d/fonts.conf
include kitty.d/cursor.conf
include kitty.d/scrollback.conf
include kitty.d/mouse.conf
include kitty.d/performance.conf
include kitty.d/terminal_bell.conf
include kitty.d/window_layout.conf
include kitty.d/tab_bar.conf
include kitty.d/color_scheme.conf
include kitty.d/advanced.conf
include kitty.d/os_specific_tweaks.conf
include kitty.d/shorcuts.conf

# vim:fileencoding=utf-8
