version: "3"

dotenv:
  - .env

env:
  PATH: '{{.HOME}}/.local/share/nvim/mason/bin:{{.PATH}}'

includes:
  dev: .taskfiles/dev.yml
  shell:
    taskfile: .taskfiles/shell.yml
    aliases: [sh]
  actions:
    taskfile: .taskfiles/actions.yml
    aliases: [gh]
  container:
    taskfile: .taskfiles/containers.yml
    aliases: [ct]

tasks:
  default:
    desc: "List all tasks"
    silent: true
    cmds:
      - task --list

  check:
    desc: "Execute all verifications (formatt + lint + tests)"
    cmds:
      - task: shell:check
      - task: shell:lint
      - task: actions:fmt-check
      - task: actions:lint
      - task: shell:test

  fmt:
    desc: "Formatear all codebase"
    cmds:
      - task: shell:fmt
      - task: actions:fmt
